# default configuration

baseURL = "/"
title   = "Ajuma"

languageCode   = "en-us"
hasCJKLanguage = true

[markup]
_merge    = "deep"
[markup.highlight]
_merge    = "deep"
noClasses = false
[markup.tableOfContents]
_merge    = "deep"
endLevel  = 2

# [menus]

# [[menus.main]]
# identifier = "home"
# name       = "Home"
# pageRef    = "/"
# weight     = 1

# [[menus.footer]]
# identifier  = "rss"
# name        = "Feeds"
# pageRef     = "/"
# weight      = 5
# [menus.footer.params]
# targetBlank = true
# format      = "rss"

#[params]
#doubleColumns = true

#[outputFormats]
#[outputFormats.myjson]
#baseName  = "myfilename"
#mediaType = "application/json"
#[outputs]
#home = ["html", "rss", "myjson"]

defaultContentLanguage = 'en'
[languages]
  [languages.de]
    contentDir = 'content/de'
    languageName = 'Deutsch'
    weight = 2
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1

[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'

[params]
  showSummary = true